config/routes.rb
Rails.application.routes.draw do
  resources :steps
  resources :problems

  root 'problems#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
    has_many :steps, dependent: :destroy
    validates :name, presence: true
    accepts_nested_attributes_for :steps, allow_destroy: true

end

app/models/step.rb
class Step < ApplicationRecord
    belongs_to :problem
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @step = Step.new(problem_id: @problem.id)
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(
        :name,
        steps_attributes: [:id, :name] 
        )
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  
  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)
    @problem = @step.problem

    respond_to do |format|
      if @step.save
        format.js
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.js
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:name, :problem_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name = nil, f = nil, association = nil, options = nil, html_options = nil, &block)
        # If a block is provided there is no name attribute and the arguments are
        # shifted with one position to the left. This re-assigns those values.
        f, association, options, html_options = name, f, association, options if block_given?
      
        options = {} if options.nil?
        html_options = {} if html_options.nil?
      
        if options.include? :locals
          locals = options[:locals]
        else
          locals = { }
        end
      
        if options.include? :partial
          partial = options[:partial]
        else
          partial = association.to_s.singularize + '_fields'
        end
      
        # Render the form fields from a file with the association name provided
        new_object = f.object.class.reflect_on_association(association).klass.new
        fields = f.fields_for(association, new_object, child_index: '') do |builder|
          render(partial, locals.merge!( f: builder))
        end
      
        # The rendered fields are sent with the link within the data-form-prepend attr
        html_options['data-form-prepend'] = raw CGI::escapeHTML( fields )
        html_options['href'] = '#'
      
        content_tag(:a, name, html_options, &block)
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small teal pt-4 footer">

    <!-- Footer Text -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase font-weight-bold">Footer text 1</h5>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae harum esse fugiat. Itaque, culpa?</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-6 mb-md-0 mb-3">

          <!-- Content -->
          <h5 class="text-uppercase font-weight-bold">Footer text 2</h5>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Optio deserunt fuga perferendis modi earum commodi aperiam temporibus quod nulla nesciunt aliquid debitis ullam omnis quos ipsam, aspernatur id excepturi hic.</p>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Text -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="/"> kasiaekiert</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Problems with steps</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Problems <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
    
    <div class="container full_height">
        <%= yield %>
    </div>
      <%= render partial: "layouts/footer" %> 
</body>
</html>

app/views/problems/_form.html.erb
<div class="container"> 
  <%= form_for(@problem, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if @problem.errors.any? %>
      <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h4>

        <ul>
        <% @problem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="form-group">
      <div class="row">
          <div class="col-sm-2">
            <%= f.label :name, "Problem name", class: "control-label" %>
          </div>
          <div class="col-sm-10 table-problemname">
            <%= f.text_field :name, class: "form-control " %>
          </div>
      </div>
    </div>

          
    <%= f.fields_for :steps do |f| %>
      <%= render 'steps_fields', f: f %>
    <% end %>

    
    <%= link_to_add_fields 'Add Steps', f, :steps, { partial: "problems/steps_fields" }, { class: 'btn btn-info' } %>

    
  <div class="form-group btn-back-edit">
      <%= f.submit class: "btn btn-primary btn-basic btn-back-edit" %>
  </div>

  <% end %>
</div>

app/views/problems/_index_steps.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-steps">
    <thead>
      <tr>
            <th>Name</th>
            <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag :tr, id: dom_id(step), class: dom_class(step) do %>
          <td><%= step.name %></td>
          <td class="link-text"><%= link_to 'Show', step %> <%= link_to 'Edit', edit_step_path(step) %> <%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <% end %>

  
    <%= link_to new_step_path, remote: true, class: 'btn btn-primary btn-newstep' do %>
      <span class="glyphicon glyphicon-plus"></span>
        New Step
    <% end %>

    </tbody>
  </table>

app/views/problems/_steps_fields.html.erb
<div class="form-group" id="tr_step_<%= f.object.id %>"> 
  <div class="row">
    <%= f.label :name, "Step name", class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-2">  
    <% if f.object.id %>
      <%= link_to 'Destroy ', f.object, class: "btn btn-warning btn-back-edit", method: :delete, data: { confirm: 'Are you sure?' }, remote: true %> 
    <% else %>
      <a href='#' class='btn btn-warning' onclick='$("#tr_step_<%= f.object.id %>").remove(); return false;' >
        Destroy 
      </a>      
    <% end %>
    </div>
  </div>
</div>

app/views/problems/_steps_table.html.erb
<table  class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% steps.each do |step| %>
      <tr id='tr_step_<%= step.id %>'>
        <td><%= step.name %></td>
        <td><%= link_to 'Edit', edit_problem_path(@problem.id) %> 
        <%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "delete_step" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/problems/destroy.js.erb
$("#tr_problem_<%= @problem.id %>").remove()

app/views/problems/edit.html.erb
<div class="page-header">
    <%= link_to problems_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to @problem, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Show
    <% end %>

  <h1 style="padding-left: 10px">Editing problem</h1>

  <%= render 'form' %>
</div>

app/views/problems/index.html.erb
  <div class="row">
    <div class="col-sm-7 page-header">
      <h1>Listing problems</h1>
    </div>

    <div class="col-sm-5 btn-back-edit">
      <%= link_to new_problem_path, class: 'btn btn-primary btn-basic' do %>
        <span class="glyphicon glyphicon-plus btn-newproblem"></span>
        New Problem
      <% end %>
    </div>
  </div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Number of steps</th>
            <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <% @problems.each do |problem| %>
        <tr id="tr_problem_<%= problem.id %>">
          <td class="link-text"><%= link_to problem.name, problem %></td>
          <td class="link-text"><%= problem.steps.count %></td>
          <td class="link-text"><%= link_to 'Show', problem %> <%= link_to 'Edit', edit_problem_path(problem) %> <%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "delete_problem" %> </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/problems/new.html.erb
<div class="page-header">
  <%= link_to problems_path, class: 'btn btn-default btn-basic' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New problem</h1>
</div>

<%= render 'form' %>

app/views/problems/new.js.erb
$('#new-step a').hide().parent().append("<%= j render 'steps/form', problem_id: @problem_id %>")

app/views/problems/show.html.erb
<div class="row">
    <div class="col-md-8 page-header">
      <h1>Show problem</h1>
    </div>

    <div class="col-md-4 btn-back-edit">
    <%= link_to problems_path, class: 'btn btn-success' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back to all problems
    <% end %>
    <%= link_to edit_problem_path(@problem), class: 'btn btn-warning' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
  </div>
</div>

Name of the problem:  <%= @problem.name %>

<p.line> </p>

<h2>Steps:</h2> 

<div id='step_table'>
  <%= render partial: 'steps_table', locals: {steps: @problem.steps} %>
</div>
<p>Add steps quickly here or click "Edit" to edit them with the problem
</p>
<%= render 'steps/form', :remote => true, locals: {steps: @problem.steps} %>

app/views/steps/_form.html.erb
<%= form_for(@step, html: { class: "form-horizontal step-form", role: "form" }, :remote => true) do |f| %>
  <%= f.hidden_field :problem_id %>
  <% if @step.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h4>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <div class="row">
          <%= f.label :new_step, class: "col-sm-2 control-label" %>
          <div class="col-sm-5">
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="col-sm-4">
          <%= f.submit class: "btn btn-primary" %>
          </div>
      </div>
  </div>
  
   
<% end %>

app/views/steps/create.js.erb
$('#step_table').html("<%= escape_javascript (render partial: 'problems/steps_table', locals: {steps: @problem.steps})%>");

app/views/steps/destroy.js.erb
$("#tr_step_<%= @step.id %>").remove()

app/views/steps/edit.html.erb
<div class="page-header">
  <%= link_to problems_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @step, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing step</h1>
</div>

<%= render 'form' %>

app/views/steps/index.html.erb
<div class="page-header">
  <h1>Listing steps</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-steps">
    <thead>
      <tr>
            <th>Name</th>
            <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag :tr, id: dom_id(step), class: dom_class(step) do %>
          <td><%= step.name %></td>
          <td class="link-text"><%= link_to 'Show', step %> <%= link_to 'Edit', edit_step_path(step) %> <%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <% end %>

  
    <%= link_to new_step_path, remote: true, class: 'btn btn-primary btn-newstep' do %>
      <span class="glyphicon glyphicon-plus"></span>
        New Step
    <% end %>

    </tbody>
  </table>
</div>

app/views/steps/new.html.erb
<div class="page-header">
  <%= link_to steps_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New step</h1>
</div>

<%= render 'form' %>

app/views/steps/show.html.erb
<div class="page-header">
  <%= link_to problems_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_step_path(@step), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show step</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @step.name %></dd>

</dl>